param(
  [switch]$SkipGradle,
  [switch]$CreateInstaller,
  [string]$RuntimeModules = $(if ($env:HICT_RUNTIME_MODULES) { $env:HICT_RUNTIME_MODULES } else { "java.se,jdk.charsets,jdk.crypto.ec,jdk.localedata,jdk.unsupported,jdk.zipfs" }),
  [string]$DistRoot = $(if ($env:HICT_PORTABLE_DIST_DIR) { $env:HICT_PORTABLE_DIST_DIR } else { (Join-Path $PSScriptRoot "..\..\build\portable") })
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Require-Command {
  param([Parameter(Mandatory = $true)][string]$Name)
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Missing required command: $Name"
  }
}

function Get-JdkTool {
  param([Parameter(Mandatory = $true)][string]$Name)
  if ($env:JAVA_HOME) {
    $candidate = Join-Path $env:JAVA_HOME "bin\$Name"
    if (Test-Path $candidate) {
      return $candidate
    }
  }
  $cmd = Get-Command $Name -ErrorAction SilentlyContinue
  if ($cmd) {
    return $cmd.Source
  }
  throw "Missing $Name. Use a full JDK, not a JRE."
}

$projectDir = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$version = (Get-Content (Join-Path $projectDir "version.txt") -Raw).Trim()
$platform = "windows-x86_64"
$appName = "HiCT"
$appDir = Join-Path $DistRoot "$appName-$version-$platform"
$artifactDir = Join-Path $projectDir "build\distributions"
$jlink = Get-JdkTool "jlink.exe"
$jpackage = Get-Command "jpackage.exe" -ErrorAction SilentlyContinue

Require-Command "powershell"

if (-not $SkipGradle) {
  Push-Location $projectDir
  try {
    & .\gradlew.bat shadowJar
  }
  finally {
    Pop-Location
  }
}

$fatJar = Get-ChildItem -Path (Join-Path $projectDir "build\libs") -Filter "*-fat.jar" |
  Sort-Object LastWriteTime |
  Select-Object -Last 1
if (-not $fatJar) {
  throw "Fat JAR was not found under $projectDir\build\libs"
}

if (Test-Path $appDir) {
  Remove-Item -Recurse -Force $appDir
}
New-Item -ItemType Directory -Force -Path $appDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $appDir "bin") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $appDir "lib") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $appDir "licenses") | Out-Null
New-Item -ItemType Directory -Force -Path $artifactDir | Out-Null

Copy-Item -Force $fatJar.FullName (Join-Path $appDir "lib\hict.jar")
Copy-Item -Force (Join-Path $projectDir "LICENSE") (Join-Path $appDir "licenses\HiCT_JVM_LICENSE")
$webUiLicense = Join-Path $projectDir "..\HiCT_WebUI\LICENSE"
if (Test-Path $webUiLicense) {
  Copy-Item -Force $webUiLicense (Join-Path $appDir "licenses\HiCT_WebUI_LICENSE")
}

@'
HiCT portable distribution notice
=================================

This package is assembled from:

  - HiCT_JVM and HiCT_WebUI, redistributed under their bundled MIT licenses.
  - The HiCT_JVM fat JAR, which contains Java dependencies and preserves the
    upstream META-INF license/notice files included in those dependency JARs.
  - A jlink runtime image created from the release JDK. The runtime\legal
    directory is intentionally kept intact and must remain with redistributed
    packages. For Eclipse Temurin/OpenJDK runtimes this includes GPLv2 with
    Classpath Exception notices and third-party runtime notices.
  - Optional bundled hictk resources inside hict.jar when toolchains-dist was
    prepared before packaging. hictk is redistributed under its MIT license and
    should be cited when .hic conversion is used.

The portable Windows release is a ZIP to avoid opaque self-extracting EXE
packing. The optional .exe is a standard jpackage installer.
'@ | Set-Content -Encoding UTF8 (Join-Path $appDir "licenses\PORTABLE_DISTRIBUTION_NOTICE.txt")

& $jlink `
  --add-modules $RuntimeModules `
  --strip-debug `
  --no-header-files `
  --no-man-pages `
  --compress=zip-6 `
  --output (Join-Path $appDir "runtime")

@'
@echo off
setlocal
set "SCRIPT_DIR=%~dp0"
for %%I in ("%SCRIPT_DIR%..") do set "APP_HOME=%%~fI"

if "%DATA_DIR%"=="" (
  set "DATA_DIR=%APP_HOME%"
)

if not exist "%DATA_DIR%" mkdir "%DATA_DIR%" >nul 2>nul

set "JAVA_EXE=%APP_HOME%\runtime\bin\java.exe"
"%JAVA_EXE%" %HICT_JAVA_OPTS% -jar "%APP_HOME%\lib\hict.jar" %*
exit /b %ERRORLEVEL%
'@ | Set-Content -Encoding ASCII (Join-Path $appDir "bin\hict.cmd")

@'
@echo off
call "%~dp0bin\hict.cmd" %*
'@ | Set-Content -Encoding ASCII (Join-Path $appDir "HiCT.cmd")

@"
HiCT portable Windows package
=============================

Run:
  HiCT.cmd
  HiCT.cmd --help
  HiCT.cmd start-server
  HiCT.cmd convert --help

The package includes:
  - HiCT_JVM fat JAR, including the built HiCT_WebUI resources
  - a jlink runtime built from the JDK used by the release runner
  - HiCT license files
  - the runtime\legal directory generated by jlink

DATA_DIR defaults to this extracted portable directory. Explicit DATA_DIR always wins.

Java runtime notices:
  The embedded runtime keeps its jlink-generated legal\ directory intact. For
  Temurin/OpenJDK builds this includes the OpenJDK GPLv2 + Classpath Exception
  notices and third-party notices shipped with the runtime.

Windows single-file note:
  This ZIP is the portable artifact. The optional .exe produced by this script is
  a standard jpackage installer because a true one-file portable Windows EXE
  requires self-extraction/custom packing, which is avoided for antivirus and
  redistribution transparency.
"@ | Set-Content -Encoding UTF8 (Join-Path $appDir "README_PORTABLE.txt")

$zipPath = Join-Path $artifactDir "$appName-$version-$platform-portable.zip"
if (Test-Path $zipPath) {
  Remove-Item -Force $zipPath
}
Compress-Archive -Path $appDir -DestinationPath $zipPath -CompressionLevel Optimal

$shaPath = Join-Path $artifactDir "$appName-$version-$platform.sha256"
$hashLines = @()
$hashLines += "$((Get-FileHash -Algorithm SHA256 $zipPath).Hash.ToLowerInvariant())  $(Split-Path -Leaf $zipPath)"

if ($CreateInstaller) {
  if (-not $jpackage) {
    throw "jpackage.exe is required for -CreateInstaller."
  }
  $installerInputDir = Join-Path $DistRoot "jpackage-input"
  $installerDestDir = Join-Path $artifactDir "jpackage"
  if (Test-Path $installerInputDir) {
    Remove-Item -Recurse -Force $installerInputDir
  }
  if (Test-Path $installerDestDir) {
    Remove-Item -Recurse -Force $installerDestDir
  }
  New-Item -ItemType Directory -Force -Path $installerInputDir | Out-Null
  New-Item -ItemType Directory -Force -Path $installerDestDir | Out-Null
  Copy-Item -Force (Join-Path $appDir "lib\hict.jar") (Join-Path $installerInputDir "hict.jar")

  $numericVersion = if ($version -match '^(\d+\.\d+\.\d+)') { $Matches[1] } else { "1.0.0" }
  & $jpackage.Source `
    --type exe `
    --name "HiCT" `
    --app-version $numericVersion `
    --vendor "Computer Technologies Laboratory ITMO University" `
    --input $installerInputDir `
    --main-jar "hict.jar" `
    --main-class "ru.itmo.ctlab.hict.hict_server.tools.HictCli" `
    --runtime-image (Join-Path $appDir "runtime") `
    --dest $installerDestDir `
    --win-console `
    --win-menu `
    --win-shortcut

  $installer = Get-ChildItem -Path $installerDestDir -Filter "*.exe" | Select-Object -First 1
  if ($installer) {
    $targetInstaller = Join-Path $artifactDir "$appName-$version-$platform-installer.exe"
    if (Test-Path $targetInstaller) {
      Remove-Item -Force $targetInstaller
    }
    Move-Item -Force $installer.FullName $targetInstaller
    $hashLines += "$((Get-FileHash -Algorithm SHA256 $targetInstaller).Hash.ToLowerInvariant())  $(Split-Path -Leaf $targetInstaller)"
  }
}

$hashLines | Set-Content -Encoding ASCII $shaPath

Write-Host "Built $zipPath"
if ($CreateInstaller) {
  Write-Host "Built optional jpackage installer in $artifactDir"
}
Write-Host "Wrote $shaPath"
